on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master 

jobs:
  build_test_job:
    name: 'Build and test job'
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: [windows-latest, ubuntu-latest]
    steps:

    - name: 'Checking out repo code'
      uses: actions/checkout@v2

    - name: 'Validate build'
      run: |
        pwd
        npm install
        npm run build
        ls
        pwd
        
    - name: 'Run L0 tests'
      run: |
        npm run test
